/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Categorie;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-02-27T13:33:09.875Z")

@Api(value = "categorie", description = "the categorie API")
public interface CategorieApi {

    @ApiOperation(value = "Ajoute  un categorie", nickname = "addCategorie", notes = "", tags={ "categorie", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/categorie",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addCategorie(@ApiParam(value = "Ajoute une categorie" ,required=true )  @Valid @RequestBody Categorie body);


    @ApiOperation(value = "supprime  un categorie", nickname = "deleteCategorie", notes = "", tags={ "categorie", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/categorie/{categorieid}",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteCategorie(@ApiParam(value = "ID of categorie to be deleted",required=true) @PathVariable("categorieid") Long categorieid);


    @ApiOperation(value = "met a jour  un categorie", nickname = "updateCategorie", notes = "", tags={ "categorie", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/categorie/{categorieid}",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateCategorie(@ApiParam(value = "ID of categorie to be updated",required=true) @PathVariable("categorieid") Long categorieid,@ApiParam(value = "Ajoute une categorie" ,required=true )  @Valid @RequestBody Categorie body);

}
