/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Competence;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-02-27T13:33:09.875Z")

@Api(value = "competence", description = "the competence API")
public interface CompetenceApi {

    @ApiOperation(value = "Ajoute  une competence", nickname = "createCompetence", notes = "", tags={ "competence", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/competence",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> createCompetence(@ApiParam(value = "Ajoute une competence" ,required=true )  @Valid @RequestBody Competence body);


    @ApiOperation(value = "supprime  un competence", nickname = "deleteCompetence", notes = "", tags={ "competence", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/competence/{competenceid}",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteCompetence(@ApiParam(value = "ID of competence to be deleted",required=true) @PathVariable("competenceid") Long competenceid);


    @ApiOperation(value = "met a jour  un competence", nickname = "updateCompetence", notes = "", tags={ "competence", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/competence/{competenceid}",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateCompetence(@ApiParam(value = "ID of competence to be updated",required=true) @PathVariable("competenceid") Long competenceid,@ApiParam(value = "Ajoute un Competence a un collaborateur" ,required=true )  @Valid @RequestBody Competence body);

}
