/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Niveau;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-02-27T13:33:09.875Z")

@Api(value = "niveau", description = "the niveau API")
public interface NiveauApi {

    @ApiOperation(value = "Ajoute  un niveau", nickname = "addNiveau", notes = "", tags={ "niveau", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/niveau",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addNiveau(@ApiParam(value = "Ajoute un Niveau a un collaborateur" ,required=true )  @Valid @RequestBody Niveau body);


    @ApiOperation(value = "supprime  un niveau", nickname = "deleteNiveau", notes = "", tags={ "niveau", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/niveau/{niveauid}",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteNiveau(@ApiParam(value = "ID of niveau to be deleted",required=true) @PathVariable("niveauid") Long niveauid);


    @ApiOperation(value = "met a jour  un niveau", nickname = "updateNiveau", notes = "", tags={ "niveau", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/niveau/{niveauid}",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateNiveau(@ApiParam(value = "ID of niveau to be updated",required=true) @PathVariable("niveauid") Long niveauid,@ApiParam(value = "Update un Niveau d'un collaborateur" ,required=true )  @Valid @RequestBody Niveau body);

}
